project_name: x2c

release:
  github:
    owner: gotidy
    name: x2c
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/x2c    
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: gotidy
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage:  https://github.com/gotidy/x2c
    description: Convert XLSX file to CSV 
    license: Apache License 2.0
    test: |
      system "#{bin}/x2c version"
    install: |-
      bin.install "x2c"
      # bash_completion.install "completions/x2c.bash" => "x2c"
      # zsh_completion.install "completions/x2c.zsh" => "_x2c"
      # fish_completion.install "completions/x2c.fish"

scoop:
  bucket:
    owner: gotidy
    name: scoop-bucket
  homepage:  https://github.com/gotidy/x2c
  description: Convert XLSX file to CSV 
  license: Apache License 2.0

